title: BANDIT - Workshop on Big Data Analysis and Illicit Trends
preposition: at
baseurl: "/bandit"
url: "https://jade-lab.github.io"

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
sass:
  style: compressed

exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js
  - _editions/
  - .jekyll-build/
  - Dockerfile
  - docker-compose.yml

collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  lang: en
  tz: "+02:00"
  show_errors: true

  link_preview:
    disable: false
    img:
      twitter: 'twitter_preview.png'
      open_graph: 'facebook_preview.png'

  talks:
    main_categories:
      - name: Full Papers
        color: info
      - name: Short Papers
        color: success
      - name: Keynote
        color: dark
    hide_icons: false

  speakers:
    show_firstname: true
